# Prefect Cloud Deployment Configuration
# Simplified version without Jinja2 templates

name: pestroutes-pipeline
prefect-version: 3.4.5

# Deployment definitions
deployments:
  # Full pipeline deployment - processes all entities for all offices
  - name: pestroutes-full-pipeline
    version: 1.0.1
    tags:
      - production
      - pestroutes
      - snowflake
      - etl
    description: |
      Complete PestRoutes to Snowflake data pipeline processing all 27 entities 
      across 17 offices with RAW and STAGING layer transformations.
      Date handling is automatic - uses yesterday's date in Pacific Time.
    
    entrypoint: flows/main_pipeline.py:pestroutes_full_pipeline
    
    parameters:
      # Dates will be auto-resolved in the flow if templates are passed
      start_date: "AUTO"
      end_date: "AUTO"
      
      # Processing options
      batch_size: 5000
      max_retries: 3
      run_staging: true
      
      # Entity filtering (empty = all entities)
      entities_to_process: []
      
      # Office filtering (empty = all offices)
      offices_to_process: []

    work_pool:
      name: default-work-pool
      
    schedule:
      # Run daily at 2 AM Mountain Time (9 AM UTC)
      cron: "0 9 * * *"
      timezone: "UTC"

  # Incremental pipeline deployment - processes only recent data
  - name: pestroutes-incremental
    version: 1.0.1
    tags:
      - incremental
      - pestroutes
      - hourly
    description: |
      Incremental PestRoutes pipeline for processing recent updates.
      Runs every 4 hours to capture near real-time changes.
    
    entrypoint: flows/main_pipeline.py:pestroutes_incremental_pipeline
    
    parameters:
      # Look back 6 hours to ensure no missed data
      hours_lookback: 6
      batch_size: 1000
      max_retries: 2
      run_staging: true

    work_pool:
      name: default-work-pool
      
    schedule:
      # Run every 4 hours
      cron: "0 */4 * * *"
      timezone: "UTC"

  # Single entity deployment - for testing or specific entity runs
  - name: pestroutes-single-entity
    version: 1.0.1
    tags:
      - testing
      - single-entity
    description: |
      Single entity pipeline for testing or processing specific entities.
      Date handling is automatic - uses yesterday's date in Pacific Time.
    
    entrypoint: flows/main_pipeline.py:pestroutes_single_entity_pipeline
    
    parameters:
      entity: "customer"
      start_date: "AUTO"
      end_date: "AUTO"
      office_ids: []  # Empty = all offices
      run_staging: true

    work_pool:
      name: default-work-pool

# Pull configuration for retrieving code
pull:
  - prefect.deployments.steps.git_clone:
      id: clone-repo
      repository: https://github.com/alta-evanunick/testing.git
      branch: main
  - prefect.deployments.steps.pip_install_requirements:
      requirements_file: ./requirements.txt
      directory: "{{ clone-repo.directory }}"