# Minimal Prefect Deployment Configuration
# PestRoutes to Snowflake Data Pipeline

name: pestroutes-pipeline
prefect-version: 3.4.5

# Deployment definitions
deployments:
  # Full pipeline deployment - processes all entities for all offices
  - name: pestroutes-full-pipeline
    version: 1.0.0
    tags:
      - production
      - pestroutes
      - snowflake
      - etl
    description: |
      Complete PestRoutes to Snowflake data pipeline processing all 27 entities 
      across 17 offices with RAW and STAGING layer transformations.
    
    entrypoint: flows/main_pipeline.py:pestroutes_full_pipeline
    
    parameters:
      # Date range for data extraction (defaults to yesterday Pacific Time)
      start_date: "2025-06-08"  # Static date for testing
      end_date: "2025-06-09"    # Static date for testing
      
      # Processing options
      batch_size: 1000  # Smaller batch for testing
      max_retries: 3
      run_staging: true
      
      # Entity filtering (test with just one entity first)
      entities_to_process: ["customer"]
      
      # Office filtering (test with fewer offices)
      offices_to_process: []

    work_pool:
      name: default-work-pool